sudo: false
language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - site/vendor
    - site/web/app/mu-plugins/sd-articles/vendor
    - site/web/app/mu-plugins/sd-events/vendor
    - site/web/app/mu-plugins/sd-shop/vendor

before_install:
  - cd site
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
  - yarn --cwd web/app/themes/sd-theme run test
  - yarn --cwd web/app/mu-plugins/sd-articles run test
  - yarn --cwd web/app/mu-plugins/sd-shop run test
