sudo: false
language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/yarn
    - site/vendor
    - site/web/app/themes/sd-theme/vendor
    - site/web/app/mu-plugins/sd-articles/vendor
    - site/web/app/mu-plugins/sd-events/vendor
    - site/web/app/mu-plugins/sd-shop/vendor
    - site/web/app/themes/sd-theme/node_modules
    - site/web/app/mu-plugins/sd-articles/node_modules
    - site/web/app/mu-plugins/sd-shop/node_modules

before_install:
  - cd site
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq nodejs yarn

install:
  - composer install -o --prefer-dist --no-interaction
  - yarn --cwd web/app/themes/sd-theme install
  - yarn --cwd web/app/mu-plugins/sd-articles install
  - yarn --cwd web/app/mu-plugins/sd-shop install

script:
  - composer test
  - yarn --cwd web/app/themes/sd-theme run test
  - yarn --cwd web/app/mu-plugins/sd-articles run test
  - yarn --cwd web/app/mu-plugins/sd-shop run test
