# ansible-playbook database-push.yml -e "env=staging site=example.com"
---
- name: Push database from development to {{ env }}
  hosts: web:&{{ env }}
  remote_user: "{{ web_user }}"

  vars:
    project_root: "{{ www_root }}/{{ site }}"
    project_web_dir: "{{ project_root }}/current"
    to_host: "{{ hostvars[env] }}"
    url_from: "{{ hostvars.development.wordpress_sites[site].site_hosts.0.canonical }}"
    url_to: "{{ to_host.wordpress_sites[site].site_hosts.0.canonical }}"
    dump_file: "{{ site | regex_replace('\\.+', '_') }}_db_dump.sql.gz"
    current_date_and_time: "{{ ansible_date_time.date | regex_replace('\\-+', '_') }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}_{{ ansible_date_time.second }}"
    backup_file: "{{ site | regex_replace('\\.+', '_') }}_{{ env }}_{{ current_date_and_time }}.sql.gz"

  tasks:
  - name: Create database dump on development
    delegate_to: development
    shell: wp db export --allow-root - | gzip > {{ dump_file }}
    args:
      chdir: "{{ project_web_dir }}"

  - name: Push database dump from development to {{ env }}
    copy:
      src: ../{{ site }}/{{ dump_file }}
      dest: "{{ project_web_dir }}/{{ dump_file }}"

  - name: Delete database dump from development
    delegate_to: development
    file:
      path: "{{ project_web_dir }}/{{ dump_file }}"
      state: absent

  - name: Export {{ env }} database before importing the dump (backup)
    shell: wp db export - | gzip > {{ backup_file }}
    args:
      chdir: "{{ project_web_dir }}"

  - name: Pull exported database from {{ env }} to development (backup)
    fetch:
      src: "{{project_web_dir}}/{{ backup_file }}"
      dest: "../{{ site }}/database_backup"
      flat: yes

  - name: Delete exported database from {{ env }} (backup)
    file:
      path: "{{ project_web_dir }}/{{ backup_file }}"
      state: absent

  - name: Import database dump on {{ env }}
    shell: gzip -c -d {{ dump_file }} | wp db import -
    args:
      chdir: "{{ project_web_dir }}"

  - name: Delete database dump from {{ env }}
    file:
      path: "{{ project_web_dir }}/{{ dump_file }}"
      state: absent

  - name: Search for {{ url_from }} and replace with {{ url_to }} on development
    command: wp search-replace '//{{ url_from }}' '//{{ url_to }}' --allow-root --all-tables
    args:
      chdir: "{{ project_web_dir }}"
    tags: ['search-replace']
