---
- type: cpt
  active: true
  name: sd-product
  supports:
  - title
  - editor
  - revisions
  - excerpt
  - thumbnail
  - custom-fields
  labels:
    has_one: Product
    has_many: Products
    text_domain: sd-shop
  config:
    public: true
    menu_icon: dashicons-cart
    query_var: true
    has_archive: true
    hierarchical: false
    menu_position: 5
    can_export: true
    capability_type: post
    rewrite:
      slug: products
- type: tax
  active: true
  name: sd-product-cat
  links:
  - sd-product
  labels:
    has_one: Product category
    has_many: Product categories
    text_domain: sd-shop
  config:
    public: true
    show_tagcloud: true
    show_in_quick_edit: true
    show_admin_column: true
    rewrite:
      slug: product-categories
      hierarchical: true
